
import type { Metadata } from "next";
import "./app.css"
import "./index.css"
import { Providers } from "@/layout/providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <Toaster richColors position="top-right" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}